### PR TITLE
S3 setup and save_csv with working tests

### PR DESCRIPTION
**Pull request by gordonmslai**

### CODE REVIEW

**Comment by aschn** [comment]
Rerunning Travis job after adding S3 credentials to Travis account.

**Comment by aschn** [comment]
I added some more tests (which caught the bug that the csv content wasn't ordered by timestamp) and moved the Django File stuff to save_csv. If this looks good to you, it looks good to me!

**Comment by gordonmslai** [comment]
Do I get to click the "Merge" button?? :D

**Comment by aschn** [comment]
Do it! :)

**Pull request merged**
